name: 🐞 Bug Report
description: Report a problem or error
labels: [ "bug" ]
assignees:
    - bendix4620
body:
  - type: textarea
    id: description
    attributes:
      label: Description
      description: A clear and concise description of the bug.
      placeholder: Describe the bug here...
    validations:
      required: true
  - type: textarea
    id: reproduction
    attributes:
      label: Reproduction
      description: Please provide a minimal reproduction to help the investigation. Please **do not** just copy your project.
      placeholder: |
        ```typst
        
        ```
    validations:
      required: true
  - type: input
    id: package_version
    attributes:
      label: Beam Version
      description: The version of Beam you are using.
    validations:
      required: true
  - type: input
    id: typst_compiler_version
    attributes:
      label: Typst Version
      description: Select the Typst version you are using.
    validations:
      required: true
  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context about the problem here.
      placeholder: Screenshots, error messages, etc.
    validations:
      required: false
